{
 "title": "Scheduler",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Schedule Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(result) (increase(scheduler_schedule_attempts_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Jobs Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "count (kube_job_failed{condition=\"true\",namespace=~\"test.*\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "count (kube_job_complete{condition=\"true\",namespace=~\"test.*\"})",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "count (kube_job_status_active{namespace=~\"test.*\"} > 0 or vector(0))",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_resource_request{resource=\"cpu\",exported_pod=~\"job-.*\"} or vector(0))",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"kwok-node-.*\",resource=\"cpu\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_resource_request{resource=\"memory\",exported_pod=~\"job-.*\"} or vector(0))",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"kwok-node-.*\",resource=\"memory\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_role{role=\"agent\"})",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=~\"Pending|Running\",namespace=~\"test.*\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"kwok-node-.*\",resource=\"pods\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Schedule Attempts Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(le) (increase(scheduler_scheduling_attempt_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Pods (by queue)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "sum by(queue) (scheduler_pending_pods)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Scheduling Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "sum by(le) (increase(scheduler_pod_scheduling_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Plugins Execution Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(plugin) (increase(scheduler_plugin_execution_duration_seconds_sum[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Sample Pods Scheduling Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(kube_pod_status_scheduled_time{pod=~\"job-.*\"} - on(uid,pod) kube_pod_created{pod=~\"job-.*\"})",
     "legendFormat": "Average scheduling time"
    }
   ]
  },
  {
   "title": "Pod Scheduling Attempts",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 16 },
   "targets": [
    {
     "expr": "sum by(le) (increase(scheduler_pod_scheduling_attempts_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Schedule Attempts Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(result) (scheduler_schedule_attempts_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduler Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 24 },
   "targets": [
    {
     "expr": "sum by(type) (scheduler_scheduler_cache_size)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Pods (by event and queue)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 24 },
   "targets": [
    {
     "expr": "sum by(queue, event) (scheduler_queue_incoming_pods_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unschedulable Pods (by plugins)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 24 },
   "targets": [
    {
     "expr": "sum by(plugin) (scheduler_unschedulable_pods)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduler Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 24 },
   "targets": [
    {
     "expr": "sum by(operation) (scheduler_goroutines)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}