apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
- namespace.yaml
- service_account.yaml
- dashboard_datasources.yaml
- dashboard_definitions.yaml
- dashboard_scheduling.yaml
- dashboard_sources.yaml
- config_secret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
