apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

resources:
- namespace.yaml
- operator_bundle.yaml
- service_account.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
- prometheus.yaml
- service.yaml
- ingress.yaml
