apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true
  externalUrl: http://172.18.0.3/prometheus
  routePrefix: /