apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver
  namespace: kube-system
  labels:
    component: kube-apiserver
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 6443
    targetPort: 6443
  selector:
    component: kube-apiserver
