apiVersion: v1
kind: Service
metadata:
  name: scheduler-plugins-scheduler
  namespace: scheduler-plugins
  labels:
    component: scheduler-plugins-scheduler
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 10259
    targetPort: 10259
  selector:
    component: scheduler
